### PR TITLE
Update depencies, fix deprecations

### PR DESCRIPTION
**Pull request by queertypes**
Tests have been run, and everything seems to be working.

### CODE REVIEW

**Comment by nh2** [comment]
@cabrera @cartazio 

Did anything come out of this?

**Comment by cabrera** [comment]
@nh2 No. Despite my initial enthusiasm to try to remedy the situation, I found myself too busy to proceed.

/cc @cartazio

**Comment by iphydf** [comment]
This PR is probably obsolete. Upstream has updated the dependencies as well.

**Comment by hvr** [comment]
This PR is obsolete as the problem at hand doesn't occur anymore in http://hackage.haskell.org/package/msgpack-1.0.0

**Pull request closed without merging**
