### PR TITLE
Fix bug in (Maybe a) fromObject decoding

### PR DESCRIPTION
**Pull request by reiddraper**

### CODE REVIEW

**Comment by iphydf** [comment]
Oh, I see, this has been done.. over a year ago. I just made #70 because I hit the same issue. Is this project dead?

**Comment by reiddraper** [comment]
> Is this project dead?

We've (@helium) given up on it.

**Comment by iphydf** [comment]
I see, are you looking for a new maintainer?

**Comment by reiddraper** [comment]
@iphydf ah, we're not the maintainer. We were just using the library, and stopped using it, partly because it's not supported.

**Comment by reiddraper** [comment]
You might also be interested in #55

**Pull request merged**
